### ISSUE TITLE
Upgrade to Orchard Core 1.0

### ISSUE THREAD

**Issue by Piedone** [EtchUK/Etch.OrchardCore.Search#20]
Perhaps not much is needed to be changed, but the suggestion is about upgrading the module to be compatible with the freshly released 1.0. version of Orchard Core.

**Comment by peterkeating** [comment]
@Piedone Agreed I don't think too much will need to change to get this to work, however I'll look to get this upgraded 👍

**Comment by peterkeating** [comment]
All done 👍

**Comment by Piedone** [comment]
Cool, thanks!
