### ISSUE TITLE
Any way that I can modify the default template?

### ISSUE THREAD

**Issue by tomswatermelon** [EtchUK/Etch.OrchardCore.Search#5]
Nice Module! Any way that I can modify the default template in liquid file overwriting? or any other methods?

Thanks.

**Comment by peterkeating** [comment]
@tomswatermelon If you've got a custom theme you should be able to override the templates by adding a template to your theme with a matching filename (e.g. `SiteSearch.Grouped.liquid`).

**Comment by tomswatermelon** [comment]
thanks for the reply! Due to rushing timelines, we have used the Graphql api to build a custom search function. Your module is definitely one of the missing piece of orchard core, I will come back in  the next project 😃

**Comment by peterkeating** [comment]
@tomswatermelon Since this module was developed, Orchard Core has significantly improved the out of the box site search so I believe this module is obsolete and you should use what comes out the box.
